// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4ayi1xj641_Ug3_ZvGY7C_3D9-jF_LmY',
    appId: '1:253716344596:web:7086bc8d8f387c8e325c01',
    messagingSenderId: '253716344596',
    projectId: 'attendance-marker-bfd87',
    authDomain: 'attendance-marker-bfd87.firebaseapp.com',
    storageBucket: 'attendance-marker-bfd87.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4ewGuOgNbquHwpHn6Yq6yk2vxS9iPcRE',
    appId: '1:253716344596:android:c6310f2b885e60c6325c01',
    messagingSenderId: '253716344596',
    projectId: 'attendance-marker-bfd87',
    storageBucket: 'attendance-marker-bfd87.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBir7l3eimcx4rr1HdsNzTq5lvtkIRMNDc',
    appId: '1:253716344596:ios:915397c9d5e7475d325c01',
    messagingSenderId: '253716344596',
    projectId: 'attendance-marker-bfd87',
    storageBucket: 'attendance-marker-bfd87.appspot.com',
    iosBundleId: 'com.example.attendanceRegister',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBir7l3eimcx4rr1HdsNzTq5lvtkIRMNDc',
    appId: '1:253716344596:ios:040365cf645f7969325c01',
    messagingSenderId: '253716344596',
    projectId: 'attendance-marker-bfd87',
    storageBucket: 'attendance-marker-bfd87.appspot.com',
    iosBundleId: 'com.example.attendanceRegister.RunnerTests',
  );
}
